# Generated by Django 2.0.2 on 2020-07-15 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200715_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imagepath',
            new_name='image',
        ),
    ]
